config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  after_action :destroy_sesstion, only: [:index]
  def index
    @session = session
    @articles = Article.all
  end

  def show
    @article = Article.find_by(id: params[:id])
    session[:datasum] = @article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
 end


private
  def article_params
    params.require(:article).permit(:title, :text )
  end
def destroy_sesstion
  session[:datasum] = nil
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def form_name
    "===Article==="
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1> Editing Article </h1>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <%if @article.errors.any?%>
    <div id='error_explanation'>
      <h2>
        <% pluralize(@article.errors.count, 'error') %> prohibited this article ffrom being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg|%>
          <li>
            <%= msg %>
          </li>
        <%end%>

      </ul>
    </div>
  <%end%>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<table>
  <%= p "Your last visit was" + "===#{@session[:datasum]["title"]}==="+ " article..." if @session[:datasum]%>
  <%= link_to 'visit again' , article_path(@session[:datasum]["id"])  if @session[:datasum] %>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
  <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1> Articles </h1>
<%= form_for :article, url: articles_path do |f| %>
<!-- In case you want to use helpers  -->
<%#= p form_name %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
 </p>
 <p>
   <%=f.label :text %>
   <%=f.text_area :text %>
 </p>
 <%=f.submit %>
<%end%>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'index page' , articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>
<%= p session[:data] %>
<%= link_to 'Index Articles', articles_path %>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'Create a Post', new_article_path %>